### ISSUE TITLE
ODBC.drivers() does not list/find drivers 

### ISSUE THREAD

**Issue by kskoeld** [JuliaDatabases/ODBC.jl#233]
Using version 0.8.2 with Julia 1.1.0
`ODBC.drivers()` only returns `0×2 Array{String,2}`
Using unixODBC 2.3.4 and testing driver and DSN with `isql` works fine.
`ODBCINI`and `ODBCINSTINI` are set correctly in environment.
How can I specify the driver?
`ODBC.ODBCDriverConnect!` looks like it could be a good candidate, but its not documented (see #232)

**Comment by laashe** [comment]
I'm experiencing the same issue, feedback here would be wonderful!

@kskoeld Have you gotten any further in connecting with ODBC?

**Comment by quinnj** [comment]
This should be fixed on master; we now ship and configure our own driver managers (iODBC/unixODBC) that should use a consistent odbcinst.ini file (on non-windows of course). Note, however, that after doing `ODBC.adddriver` or `ODBC.removedriver`, you often need to restart your julia session to see the changes reflected in `ODBC.drivers()` since the driver manager will often cache the file per session.
