### ISSUE TITLE
Documentation: Add example of creating a DSN-based connection

### ISSUE THREAD

**Issue by metanoid** [JuliaDatabases/ODBC.jl#266]
I'm struggling to work out how to connect to a Netezza DSN after the recent rewrite.

Previously, I was using:
```julia
using ODBC
conn = ODBC.DSN("NetezzaDSN", "myusername", "mypassword")
```
where `NetezzaDSN` is the name of a 64-bit ODBC connection on Windows.
After the recent rewrite, the documentation suggests the alternative syntax:

```julia
# using Pkg; Pkg.add("ODBC#master")
using ODBC
conn = DBInterface.connect("NetezzaDSN")
```

However, this results in a NotImplemented error:
```
ERROR: DBInterface.NotImplementedError("`DBInterface.connect` not implemented for `Netezza`")
```

An example in the documentation of connecting via Windows ODBC DSNs would be very helpful.

**Comment by quinnj** [comment]
Ah, thanks for pointing this out; the doc string was wrong for `DBInterface.connect`, you have to include the type of connection as the first argument, so it should be `DBInterface.connect(ODBC.Connection, "NetezzaDSN")`. Alternatively, you can just do `ODBC.Connection("NetezzaDSN")`, which should also now be fixed in the docs.
